name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Create env file
        run: |
          echo "OSS_ACCESS_KEY=${{ secrets.OSS_ACCESS_KEY }}" > .env
          echo "OSS_SECRET_KEY=${{ secrets.OSS_SECRET_KEY }}" >> .env
          echo "OSS_BUCKET=${{ secrets.OSS_BUCKET }}" >> .env
          echo "PUB_API_APP_ID=${{ secrets.PUB_API_APP_ID }}" >> .env
          echo "PUB_API_APP_SECRET=${{ secrets.PUB_API_APP_SECRET }}" >> .env
        shell: bash

      - name: Install dependencies
        run: |
          yarn install
          sudo apt-get update
          sudo apt-get install -y libc6-dev-i386 build-essential file

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup NDK
        run: |
          yes | sdkmanager --install "ndk;21.4.7075529" "cmake;3.18.1"
          echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --info
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK }}

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '36.0.0'

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
